### PR TITLE
Add `requireSchemeOrWww` option

### LINKED ISSUE #24: Support `url-regex` options
Hi, 

Thanks for this great tool, I'm trying to find links in a string that looks something like this "This is a string with a link foobar.com". Looking at url-regex, this is possible with strict = false.

Is it possible to include that as an option for get-urls?

Thanks again.
Johnson

### LINKED ISSUE #48: Add option to get URLs without a protocol
Hey everyone, maybe you can help me with this issue. 

I have this url:
media1.giphy.com/media/Yg12tqyJwylsk/giphy.gif

But it is not being recognized.

my code:

`getUrls = require('get-urls');
 let a = this.getUrls(text);`

Hope you can help me :)

Thanky you very much!

### PR DESCRIPTION
**Pull request by osdiab**
Fixes #48 
Fixes #24 

Not sure how this ought to work with the `extractFromQueryString` param since I never use that - should it just forward the flag there?

### CODE REVIEW

**Comment by sindresorhus** [comment]
The option name makes sense for the regex, but not here, as including www and protocol-less URLs is actually **looser**. I think it should be called `requireScheme` and default to true.

**Comment by sindresorhus** [comment]
> Not sure how this ought to work with the extractFromQueryString param since I never use that - should it just forward the flag there?

I don't think it should apply there as it will be too ambiguous.

**Comment by osdiab** [comment]
@sindresorhus edited with comments

**Comment by sindresorhus** [comment]
Hmm, sorry, I missed that it also affects www, so the option should be `requireSchemeOrWww` to be explicit. Also use the scheme word instead of protocol.

**Comment by sindresorhus** [comment]
Maybe also add a note that when it’s off it will match things like `unicorn.education`.

**Comment by osdiab** [comment]
back to you @sindresorhus

**Comment by nestarz** [comment]
Can we give the user the hand to the list of the TLD ? For example, .onions are not captured using this.

**Comment by osdiab** [comment]
I actually added an issue to url-regex earlier for that exact request, although for a different reason: https://github.com/kevva/url-regex/issues/65

Would be helpful to advocate your reason for wanting this there!

With that in mind maybe it is better to just do #24 instead for maximum flexibility with less API surface, what do you think @sindresorhus ?

**Comment by osdiab** [comment]
@nestarz made a PR for that feature, which if passed maybe can end up here too. https://github.com/kevva/url-regex/pull/66

**Comment by sindresorhus** [comment]
> With that in mind maybe it is better to just do #24 instead for maximum flexibility with less API surface, what do you think @sindresorhus ?

No, I want to explicitly only expose options that make sense.

**Pull request merged**
