### PR TITLE
Drop using `re2`

### PR DESCRIPTION
**Pull request by sindresorhus**

### CODE REVIEW

**Comment by jonluca** [comment]
Why is this blocked by that issue? It doesn't look like super-regex uses `url-regex-safe` or `re2`?

**Comment by sindresorhus** [comment]
> I have my own way of ensuring safety, and re2 is problematic, as the regex it returns is not a proper RegExp instance.

And super-regex validates that the regex is a proper regex.

**Comment by jonluca** [comment]
Ah gotcha, yes makes sense

**Comment by sindresorhus** [comment]
@titanism Thanks for fixing this 👍

**Pull request merged**
